### ISSUE TITLE
Error daily_observed_latlng

### ISSUE THREAD

**Issue by patarol** [aWhereAPI/aWhere-R-Library#19]
I'm trying to retrieve historical data using `aWhereAPI` R Package.
When I run the `daily_observed_latlng` it throws an error:

`#Error in checkCredentials(keyToUse, secretToUse, tokenToUse) : 
  object 'awhereEnv75247' not found`

I tried to use my API key, but same error is returned. 

Any help would be appreciated. 

Thank you in advance.
***
## My code:

```
aWhereAPI::daily_observed_latlng(latitude=51.52771,
                                 longitude=-0.1290532,
                                 day_start="2017-01-01",
                                 day_end="2018-03-01",
                                 keyToUse = "fzfHV6W48eN8hgexCfCiYvhiJ5RyRe1v")
```

**Comment by colinloftin-awhere** [comment]
@patarol Your key and secret are used for requesting an API token which is what the various API requests use to verify access. So you'll need to also pass in your token to the function. Or, you can run `get_token()` passing in your key and secret. This will return and store your API token and allow the package functions to easily reference this token without you having to manually pass in your credentials each time you call a function.
